ALTER TABLE public.companies
  ADD COLUMN legal_name text,
  ADD COLUMN trade_name text,
  ADD COLUMN founded_date text,
  ADD COLUMN main_activity text,
  ADD COLUMN main_activity_code integer,
  ADD COLUMN side_activities jsonb DEFAULT '[]',
  ADD COLUMN legal_nature text,
  ADD COLUMN company_size text,
  ADD COLUMN simples_optant boolean DEFAULT false,
  ADD COLUMN simei_optant boolean DEFAULT false,
  ADD COLUMN equity numeric DEFAULT 0,
  ADD COLUMN registration_status text,
  ADD COLUMN status_date text,
  ADD COLUMN address_street text,
  ADD COLUMN address_number text,
  ADD COLUMN address_district text,
  ADD COLUMN address_details text,
  ADD COLUMN address_zip text,
  ADD COLUMN city text,
  ADD COLUMN state text,
  ADD COLUMN phones jsonb DEFAULT '[]',
  ADD COLUMN emails jsonb DEFAULT '[]',
  ADD COLUMN members jsonb DEFAULT '[]',
  ADD COLUMN is_head boolean;